.\" Copyright 2014 Google Inc.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are
.\" met:
.\"
.\" * Redistributions of source code must retain the above copyright
.\"   notice, this list of conditions and the following disclaimer.
.\" * Redistributions in binary form must reproduce the above copyright
.\"   notice, this list of conditions and the following disclaimer in the
.\"   documentation and/or other materials provided with the distribution.
.\" * Neither the name of Google Inc. nor the names of its contributors
.\"   may be used to endorse or promote products derived from this software
.\"   without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
.\" OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd November 5, 2014
.Dt SHTK_CLI_WARNING 3
.Os
.Sh NAME
.Nm shtk_cli_warning
.Nd Prints a warning message
.Sh LIBRARY
shtk_import cli
.Sh SYNOPSIS
.Nm shtk_cli_warning
.Ar message1
.Op Ar .. messageN
.Sh DESCRIPTION
The
.Nm
function prints the given warning message to stderr.
The message can be provided as one or more arguments as depicted by
.Ar message1
to
.Ar messageN ;
all arguments are concatenated together into a single line.
.Pp
The printed message has the following form, where
.Sq progname
is determined by
.Xr shtk_cli_progname 3 :
.Bd -literal -offset indent
progname: W: message1 .. messageN
.Ed
.Pp
.Nm
should be used to inform the user of erroneous but non-critical conditions that
permit the script to continue execution.
.Sh SEE ALSO
.Xr shtk 3 ,
.Xr shtk_cli 3
.Sh HISTORY
.Nm
first appeared in
.Nm shtk
1.0.
