.Dd February 20, 2020
.Dt SHTK_GIT 3
.Os
.Sh NAME
.Nm git
.Nd Utilities to invoke GIT and wrappers to simplify its operation
.Sh LIBRARY
shtk_import
.Nm
.Sh DESCRIPTION
The
.Nm
module provides utilities to invoke the GIT utility and to simplify its
operation.
.Sh SEE ALSO
.Xr shtk 3 ,
.Xr shtk_git_pull 3 ,
.Xr shtk_git_gethash 3
