.\" Copyright 2014 Google Inc.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are
.\" met:
.\"
.\" * Redistributions of source code must retain the above copyright
.\"   notice, this list of conditions and the following disclaimer.
.\" * Redistributions in binary form must reproduce the above copyright
.\"   notice, this list of conditions and the following disclaimer in the
.\"   documentation and/or other materials provided with the distribution.
.\" * Neither the name of Google Inc. nor the names of its contributors
.\"   may be used to endorse or promote products derived from this software
.\"   without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
.\" OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd November 6, 2014
.Dt SHTK_CONFIG_UNSET 3
.Os
.Sh NAME
.Nm shtk_config_unset
.Nd Clears a configuration variable
.Sh LIBRARY
shtk_import config
.Sh SYNOPSIS
.Nm
.Ar var_name
.Sh DESCRIPTION
The
.Nm
function unsets the value of the configuration variable
.Ar var_name .
It is OK to call
.Nm
even if
.Ar var_name
has never been previously set.
However, the given configuration variable must be a valid configuration variable
as previously specified by a call to
.Xr shtk_config_init 3 .
.Sh ERRORS
If
.Ar var_name
is invalid because it has not been registered as a valid configuration variable
with a call to
.Xr shtk_config_init 3 ,
execution terminates with an error.
.Sh SEE ALSO
.Xr shtk 3 ,
.Xr shtk_config 3
.Sh HISTORY
.Nm
first appeared in
.Nm shtk
1.0.
