name: Lint

on: push

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: cargo-bins/cargo-binstall@main
            - run: cargo binstall --no-confirm prek
            - run: prek run --all-files
