name: Test

on: [push, pull_request]

jobs:
    bash-nothing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get install bash
            - run: sudo apt-get remove git
            - run: ./.github/workflows/build.sh bash ""

    bash-everything:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get install bash cvs git
            - run: ./.github/workflows/build.sh bash "cvs git"

    dash-nothing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get install dash
            - run: sudo apt-get remove git
            - run: ./.github/workflows/build.sh dash ""

    dash-everything:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get install dash cvs git
            - run: ./.github/workflows/build.sh dash "cvs git"

    mksh-nothing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get install mksh
            - run: sudo apt-get remove git
            - run: ./.github/workflows/build.sh ksh ""

    mksh-everything:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get install mksh cvs git
            - run: ./.github/workflows/build.sh ksh "cvs git"

    zsh-nothing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get install zsh
            - run: sudo apt-get remove git
            - run: ./.github/workflows/build.sh zsh ""

    zsh-everything:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get install zsh cvs git
            - run: ./.github/workflows/build.sh zsh "cvs git"
